name: Test

on: 
  pull_request: {}
  push:
    branches: "*"
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          pip install .[test]""

      - run: isort --diff .
      - run: black --check .
      - run: flake8
      - run: pytest --cov --cov-fail-under=80

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t best_practices:test

      - name: Smoke test docker image
        run: |
          docker run --rm best_practices:test 10
